-- Final consolidated schema for RCAS-Project
-- Generated by code assistant: combines core accounting, inventory, payroll, subscriptions
-- Use UUIDs for PKs. Auth is handled by Supabase `auth.users`.

-- Enable uuid extension (if not already)
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-----------------------------
-- 1. Core: Companies & Branches
-----------------------------
CREATE TABLE IF NOT EXISTS companies (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  user_id UUID REFERENCES auth.users(id) NOT NULL, -- owner / creator
  name TEXT NOT NULL,
  name_arabic TEXT,
  registration_no TEXT,
  tax_number TEXT,
  address JSONB,
  country TEXT,
  currency_id UUID, -- reference to `currencies` if implemented
  metadata JSONB,
  created_at TIMESTAMPTZ DEFAULT now(),
  updated_at TIMESTAMPTZ DEFAULT now()
);

CREATE TABLE IF NOT EXISTS branches (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  company_id UUID NOT NULL REFERENCES companies(id) ON DELETE CASCADE,
  name TEXT NOT NULL,
  name_arabic TEXT,
  address JSONB,
  phone TEXT,
  enabled BOOLEAN DEFAULT true,
  created_at TIMESTAMPTZ DEFAULT now(),
  updated_at TIMESTAMPTZ DEFAULT now()
);

-----------------------------
-- 2. Accounting: Groups & Ledgers
-----------------------------
CREATE TABLE IF NOT EXISTS account_groups (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  company_id UUID NOT NULL REFERENCES companies(id) ON DELETE CASCADE,
  parent_id UUID REFERENCES account_groups(id),
  name TEXT NOT NULL,
  name_arabic TEXT,
  nature TEXT, -- e.g., 'Assets','Liabilities','Income','Expenses'
  created_at TIMESTAMPTZ DEFAULT now()
);

CREATE TABLE IF NOT EXISTS ledgers (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  company_id UUID NOT NULL REFERENCES companies(id) ON DELETE CASCADE,
  group_id UUID REFERENCES account_groups(id),
  name TEXT NOT NULL,
  name_arabic TEXT,
  code TEXT, -- optional ledger code / GL code
  opening_balance NUMERIC DEFAULT 0,
  currency_id UUID,
  created_at TIMESTAMPTZ DEFAULT now(),
  updated_at TIMESTAMPTZ DEFAULT now()
);

-----------------------------
-- 3. Inventory: Groups, Units, Godowns, Items
-----------------------------
CREATE TABLE IF NOT EXISTS stock_groups (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  company_id UUID NOT NULL REFERENCES companies(id) ON DELETE CASCADE,
  name TEXT NOT NULL,
  name_arabic TEXT,
  created_at TIMESTAMPTZ DEFAULT now()
);

CREATE TABLE IF NOT EXISTS units (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  company_id UUID NOT NULL REFERENCES companies(id) ON DELETE CASCADE,
  name TEXT NOT NULL,
  symbol TEXT,
  created_at TIMESTAMPTZ DEFAULT now()
);

CREATE TABLE IF NOT EXISTS godowns (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  company_id UUID NOT NULL REFERENCES companies(id) ON DELETE CASCADE,
  name TEXT NOT NULL,
  name_arabic TEXT,
  created_at TIMESTAMPTZ DEFAULT now()
);

CREATE TABLE IF NOT EXISTS stock_items (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  company_id UUID NOT NULL REFERENCES companies(id) ON DELETE CASCADE,
  sku TEXT UNIQUE,
  name TEXT NOT NULL,
  name_arabic TEXT,
  group_id UUID REFERENCES stock_groups(id),
  unit_id UUID REFERENCES units(id),
  godown_id UUID REFERENCES godowns(id),
  purchase_price NUMERIC DEFAULT 0,
  selling_price NUMERIC DEFAULT 0,
  tax_percent NUMERIC DEFAULT 0,
  track_stock BOOLEAN DEFAULT true,
  reorder_level NUMERIC DEFAULT 0,
  metadata JSONB,
  created_at TIMESTAMPTZ DEFAULT now(),
  updated_at TIMESTAMPTZ DEFAULT now()
);

-----------------------------
-- 4. Vouchers, Voucher Items, Ledger Entries
-----------------------------
CREATE TABLE IF NOT EXISTS voucher_types (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  company_id UUID NOT NULL REFERENCES companies(id) ON DELETE CASCADE,
  name TEXT NOT NULL,
  parent_type TEXT,
  abbreviation TEXT,
  created_at TIMESTAMPTZ DEFAULT now()
);

CREATE TABLE IF NOT EXISTS vouchers (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  company_id UUID NOT NULL REFERENCES companies(id) ON DELETE CASCADE,
  branch_id UUID REFERENCES branches(id),
  voucher_type_id UUID REFERENCES voucher_types(id),
  number TEXT, -- manual/auto numbering
  date DATE DEFAULT CURRENT_DATE,
  narration TEXT,
  total_amount NUMERIC DEFAULT 0,
  status TEXT DEFAULT 'draft', -- draft, posted, cancelled
  created_by UUID REFERENCES auth.users(id),
  created_at TIMESTAMPTZ DEFAULT now(),
  updated_at TIMESTAMPTZ DEFAULT now()
);

CREATE TABLE IF NOT EXISTS voucher_items (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  voucher_id UUID NOT NULL REFERENCES vouchers(id) ON DELETE CASCADE,
  stock_item_id UUID REFERENCES stock_items(id),
  ledger_id UUID REFERENCES ledgers(id),
  description TEXT,
  quantity NUMERIC DEFAULT 1,
  unit_id UUID REFERENCES units(id),
  rate NUMERIC DEFAULT 0,
  amount NUMERIC DEFAULT 0,
  tax_percent NUMERIC DEFAULT 0,
  created_at TIMESTAMPTZ DEFAULT now()
);

CREATE TABLE IF NOT EXISTS voucher_ledger_entries (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  voucher_id UUID NOT NULL REFERENCES vouchers(id) ON DELETE CASCADE,
  ledger_id UUID NOT NULL REFERENCES ledgers(id),
  debit NUMERIC DEFAULT 0,
  credit NUMERIC DEFAULT 0,
  sequence INT DEFAULT 0,
  created_at TIMESTAMPTZ DEFAULT now()
);

-----------------------------
-- 5. Payroll & HR (simplified)
-----------------------------
CREATE TABLE IF NOT EXISTS employees (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  company_id UUID NOT NULL REFERENCES companies(id) ON DELETE CASCADE,
  employee_no TEXT,
  first_name TEXT,
  last_name TEXT,
  name_arabic TEXT,
  email TEXT,
  phone TEXT,
  hire_date DATE,
  active BOOLEAN DEFAULT true,
  meta JSONB,
  created_at TIMESTAMPTZ DEFAULT now(),
  updated_at TIMESTAMPTZ DEFAULT now()
);

CREATE TABLE IF NOT EXISTS salary_components (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  company_id UUID NOT NULL REFERENCES companies(id) ON DELETE CASCADE,
  name TEXT NOT NULL,
  type TEXT, -- earning / deduction
  created_at TIMESTAMPTZ DEFAULT now()
);

CREATE TABLE IF NOT EXISTS payrolls (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  company_id UUID NOT NULL REFERENCES companies(id) ON DELETE CASCADE,
  employee_id UUID REFERENCES employees(id),
  period_start DATE,
  period_end DATE,
  gross_pay NUMERIC DEFAULT 0,
  deductions NUMERIC DEFAULT 0,
  net_pay NUMERIC DEFAULT 0,
  processed_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ DEFAULT now()
);

-----------------------------
-- 6. Subscription Keys & Payments
-----------------------------
CREATE TABLE IF NOT EXISTS subscription_keys (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  key_code TEXT UNIQUE NOT NULL,
  plan_type TEXT NOT NULL DEFAULT 'premium',
  status TEXT NOT NULL DEFAULT 'active', -- active, used, revoked
  claimed_by UUID REFERENCES auth.users(id),
  claimed_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ DEFAULT now(),
  metadata JSONB
);

CREATE TABLE IF NOT EXISTS payments (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  user_id UUID REFERENCES auth.users(id),
  company_id UUID REFERENCES companies(id),
  amount NUMERIC NOT NULL,
  currency TEXT,
  status TEXT DEFAULT 'pending',
  provider_id TEXT,
  created_at TIMESTAMPTZ DEFAULT now()
);

-----------------------------
-- 7. Utilities: id_counters, settings, currencies
-----------------------------
CREATE TABLE IF NOT EXISTS id_counters (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  company_id UUID REFERENCES companies(id),
  key TEXT NOT NULL,
  last_value BIGINT DEFAULT 0
);

CREATE TABLE IF NOT EXISTS settings (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  company_id UUID REFERENCES companies(id),
  key TEXT NOT NULL,
  value JSONB,
  updated_at TIMESTAMPTZ DEFAULT now()
);

CREATE TABLE IF NOT EXISTS currencies (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  code TEXT UNIQUE NOT NULL,
  name TEXT,
  symbol TEXT
);

-----------------------------
-- 8. Helpful functions (safe defaults)
-----------------------------
CREATE OR REPLACE FUNCTION generate_license_key()
RETURNS TEXT LANGUAGE plpgsql AS $$
DECLARE
  chars TEXT[] := '{A,B,C,D,E,F,G,H,J,K,L,M,N,P,Q,R,S,T,U,V,W,X,Y,Z,2,3,4,5,6,7,8,9}';
  res TEXT := 'RCAS-';
  i INT;
BEGIN
  FOR i IN 1..4 LOOP
    res := res || chars[1 + floor(random() * (array_length(chars,1)-1))::int];
  END LOOP;
  res := res || '-';
  FOR i IN 1..4 LOOP
    res := res || chars[1 + floor(random() * (array_length(chars,1)-1))::int];
  END LOOP;
  RETURN res;
END;
$$;

CREATE OR REPLACE FUNCTION claim_subscription_key(input_key TEXT)
RETURNS JSON LANGUAGE plpgsql SECURITY DEFINER AS $$
DECLARE
  key_rec RECORD;
  uid UUID := auth.uid();
BEGIN
  IF uid IS NULL THEN
    RETURN json_build_object('success', false, 'message', 'not_authenticated');
  END IF;
  SELECT * INTO key_rec FROM subscription_keys WHERE key_code = input_key AND status = 'active' FOR UPDATE;
  IF NOT FOUND THEN
    RETURN json_build_object('success', false, 'message', 'invalid_or_used');
  END IF;
  UPDATE subscription_keys SET status = 'used', claimed_by = uid, claimed_at = now() WHERE id = key_rec.id;
  RETURN json_build_object('success', true, 'message', 'claimed', 'plan', key_rec.plan_type);
END;
$$;

-----------------------------
-- 9. Row Level Security helpers & policies
-----------------------------
-- Helper: check company ownership
CREATE OR REPLACE FUNCTION is_company_owner(cid UUID)
RETURNS BOOLEAN
LANGUAGE sql
SECURITY DEFINER
AS $$
  SELECT EXISTS (SELECT 1 FROM companies WHERE id = cid AND user_id = auth.uid());
$$;

ALTER FUNCTION public.is_company_owner(UUID) SET search_path = public;

-- Enable RLS and add ownership policies for core tables
ALTER TABLE IF EXISTS companies ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Users can manage their own companies" ON companies;
CREATE POLICY "Users can manage their own companies" ON companies
  FOR ALL TO authenticated
  USING (user_id = auth.uid())
  WITH CHECK (user_id = auth.uid());

ALTER TABLE IF EXISTS branches ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Access branches by company ownership" ON branches;
CREATE POLICY "Access branches by company ownership" ON branches
  FOR ALL TO authenticated
  USING (is_company_owner(company_id))
  WITH CHECK (is_company_owner(company_id));

ALTER TABLE IF EXISTS account_groups ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Access account_groups by company ownership" ON account_groups;
CREATE POLICY "Access account_groups by company ownership" ON account_groups
  FOR ALL TO authenticated
  USING (is_company_owner(company_id))
  WITH CHECK (is_company_owner(company_id));

ALTER TABLE IF EXISTS ledgers ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Access ledgers by company ownership" ON ledgers;
CREATE POLICY "Access ledgers by company ownership" ON ledgers
  FOR ALL TO authenticated
  USING (is_company_owner(company_id))
  WITH CHECK (is_company_owner(company_id));

ALTER TABLE IF EXISTS stock_groups ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Access stock_groups by company ownership" ON stock_groups;
CREATE POLICY "Access stock_groups by company ownership" ON stock_groups
  FOR ALL TO authenticated
  USING (is_company_owner(company_id))
  WITH CHECK (is_company_owner(company_id));

ALTER TABLE IF EXISTS units ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Access units by company ownership" ON units;
CREATE POLICY "Access units by company ownership" ON units
  FOR ALL TO authenticated
  USING (is_company_owner(company_id))
  WITH CHECK (is_company_owner(company_id));

ALTER TABLE IF EXISTS godowns ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Access godowns by company ownership" ON godowns;
CREATE POLICY "Access godowns by company ownership" ON godowns
  FOR ALL TO authenticated
  USING (is_company_owner(company_id))
  WITH CHECK (is_company_owner(company_id));

ALTER TABLE IF EXISTS stock_items ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Access stock_items by company ownership" ON stock_items;
CREATE POLICY "Access stock_items by company ownership" ON stock_items
  FOR ALL TO authenticated
  USING (is_company_owner(company_id))
  WITH CHECK (is_company_owner(company_id));

ALTER TABLE IF EXISTS voucher_types ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Access voucher_types by company ownership" ON voucher_types;
CREATE POLICY "Access voucher_types by company ownership" ON voucher_types
  FOR ALL TO authenticated
  USING (is_company_owner(company_id))
  WITH CHECK (is_company_owner(company_id));

ALTER TABLE IF EXISTS vouchers ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Access vouchers by company ownership" ON vouchers;
CREATE POLICY "Access vouchers by company ownership" ON vouchers
  FOR ALL TO authenticated
  USING (is_company_owner(company_id))
  WITH CHECK (is_company_owner(company_id));

ALTER TABLE IF EXISTS voucher_items ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Access voucher_items by voucher ownership" ON voucher_items;
CREATE POLICY "Access voucher_items by voucher ownership" ON voucher_items
  FOR ALL TO authenticated
  USING (EXISTS (SELECT 1 FROM vouchers v WHERE v.id = voucher_id AND is_company_owner(v.company_id)))
  WITH CHECK (EXISTS (SELECT 1 FROM vouchers v WHERE v.id = voucher_id AND is_company_owner(v.company_id)));

ALTER TABLE IF EXISTS voucher_ledger_entries ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Access voucher_ledger_entries by voucher ownership" ON voucher_ledger_entries;
CREATE POLICY "Access voucher_ledger_entries by voucher ownership" ON voucher_ledger_entries
  FOR ALL TO authenticated
  USING (EXISTS (SELECT 1 FROM vouchers v WHERE v.id = voucher_id AND is_company_owner(v.company_id)))
  WITH CHECK (EXISTS (SELECT 1 FROM vouchers v WHERE v.id = voucher_id AND is_company_owner(v.company_id)));

ALTER TABLE IF EXISTS employees ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Access employees by company ownership" ON employees;
CREATE POLICY "Access employees by company ownership" ON employees
  FOR ALL TO authenticated
  USING (is_company_owner(company_id))
  WITH CHECK (is_company_owner(company_id));

ALTER TABLE IF EXISTS payrolls ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Access payrolls by company ownership" ON payrolls;
CREATE POLICY "Access payrolls by company ownership" ON payrolls
  FOR ALL TO authenticated
  USING (is_company_owner(company_id))
  WITH CHECK (is_company_owner(company_id));

ALTER TABLE IF EXISTS salary_components ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Access salary_components by company ownership" ON salary_components;
CREATE POLICY "Access salary_components by company ownership" ON salary_components
  FOR ALL TO authenticated
  USING (is_company_owner(company_id))
  WITH CHECK (is_company_owner(company_id));

ALTER TABLE IF EXISTS id_counters ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Access id_counters by company ownership" ON id_counters;
CREATE POLICY "Access id_counters by company ownership" ON id_counters
  FOR ALL TO authenticated
  USING (company_id IS NOT NULL AND is_company_owner(company_id))
  WITH CHECK (company_id IS NOT NULL AND is_company_owner(company_id));

ALTER TABLE IF EXISTS settings ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Access settings by company ownership" ON settings;
CREATE POLICY "Access settings by company ownership" ON settings
  FOR ALL TO authenticated
  USING (company_id IS NOT NULL AND is_company_owner(company_id))
  WITH CHECK (company_id IS NOT NULL AND is_company_owner(company_id));

-- subscription_keys: users can view keys they claimed; service_role has full access
ALTER TABLE IF EXISTS subscription_keys ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Users can view own subscription keys" ON subscription_keys;
CREATE POLICY "Users can view own subscription keys" ON subscription_keys
  FOR SELECT TO authenticated
  USING (claimed_by = auth.uid());

DROP POLICY IF EXISTS "Service role full access" ON subscription_keys;
CREATE POLICY "Service role full access" ON subscription_keys
  FOR ALL
  USING (auth.role() = 'service_role');

ALTER TABLE IF EXISTS payments ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Access payments by user or company" ON payments;
CREATE POLICY "Access payments by user or company" ON payments
  FOR ALL TO authenticated
  USING (user_id = auth.uid() OR (company_id IS NOT NULL AND is_company_owner(company_id)))
  WITH CHECK (user_id = auth.uid() OR (company_id IS NOT NULL AND is_company_owner(company_id)));

-- End of final_schema.sql
