-- RCAS Supabase Schema Setup
-- Run this script in your Supabase SQL Editor to create the necessary tables.

-- Enable UUID extension if needed (though we use bigint/int8 for IDs mostly in this app)
create extension if not exists "uuid-ossp";

-- 1. Users Table (Managed by Supabase Auth usually, but app has its own User entity)
-- Note: The app's 'User' entity is separate from Supabase Auth. 
-- You might want to sync them, but for now, we create a table for the app's User entity.
CREATE TABLE IF NOT EXISTS "User" (
  id bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  username text,
  password text, -- Note: Store hashed passwords in production!
  full_name text,
  email text,
  role text,
  allowed_companies jsonb, -- Array of company IDs
  avatar text,
  created_at timestamptz DEFAULT now()
);

-- 2. Settings (Global App Settings)
CREATE TABLE IF NOT EXISTS "Settings" (
  id bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  company_name text,
  base_currency text,
  created_at timestamptz DEFAULT now()
  -- Add other settings fields as needed (jsonb is good here)
);
ALTER TABLE "Settings" ADD COLUMN IF NOT EXISTS config jsonb; -- Flexible storage for other settings

-- 3. Company
CREATE TABLE IF NOT EXISTS "Company" (
  id bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  name text,
  address text,
  phone text,
  email text,
  vat_number text,
  created_at timestamptz DEFAULT now()
);

-- 4. Branch
CREATE TABLE IF NOT EXISTS "Branch" (
  id bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  company_id bigint REFERENCES "Company"(id),
  name text,
  location text,
  type text, -- 'Salon', 'Retail', etc.
  created_at timestamptz DEFAULT now()
);

-- 5. Common Entities (Need company_id)
-- We will create a generic function to easily create other tables
-- But for SQL script, we list them out.

CREATE TABLE IF NOT EXISTS "Currency" (
  id bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  company_id bigint,
  name text,
  symbol text,
  exchange_rate numeric,
  created_at timestamptz DEFAULT now()
);

CREATE TABLE IF NOT EXISTS "AccountGroup" (
  id bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  company_id bigint,
  name text,
  parent_group_id bigint,
  primary_group text,
  created_at timestamptz DEFAULT now()
);

CREATE TABLE IF NOT EXISTS "Ledger" (
  id bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  company_id bigint,
  name text,
  group_id bigint,
  opening_balance numeric,
  created_at timestamptz DEFAULT now()
);

CREATE TABLE IF NOT EXISTS "StockGroup" (
  id bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  company_id bigint,
  name text,
  parent_id bigint,
  created_at timestamptz DEFAULT now()
);

CREATE TABLE IF NOT EXISTS "Unit" (
  id bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  company_id bigint,
  name text,
  symbol text,
  created_at timestamptz DEFAULT now()
);

CREATE TABLE IF NOT EXISTS "StockItem" (
  id bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  company_id bigint,
  name text,
  group_id bigint,
  unit_id bigint,
  opening_quantity numeric,
  opening_rate numeric,
  opening_value numeric,
  part_number text,
  description text,
  created_at timestamptz DEFAULT now()
);

CREATE TABLE IF NOT EXISTS "Godown" (
  id bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  company_id bigint,
  name text,
  location text,
  created_at timestamptz DEFAULT now()
);

CREATE TABLE IF NOT EXISTS "CostCenter" (
  id bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  company_id bigint,
  name text,
  created_at timestamptz DEFAULT now()
);

CREATE TABLE IF NOT EXISTS "VoucherType" (
  id bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  company_id bigint,
  name text,
  type text, -- 'Sales', 'Purchase', etc.
  prefix text,
  created_at timestamptz DEFAULT now()
);

CREATE TABLE IF NOT EXISTS "Voucher" (
  id bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  company_id bigint,
  voucher_number text,
  date date,
  voucher_type_id bigint,
  ledger_id bigint, -- Party ledger
  narration text,
  total_amount numeric,
  created_at timestamptz DEFAULT now()
);

CREATE TABLE IF NOT EXISTS "VoucherItem" (
  id bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  voucher_id bigint REFERENCES "Voucher"(id),
  stock_item_id bigint,
  quantity numeric,
  rate numeric,
  amount numeric,
  created_at timestamptz DEFAULT now()
);

CREATE TABLE IF NOT EXISTS "VoucherLedgerEntry" (
  id bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  voucher_id bigint REFERENCES "Voucher"(id),
  ledger_id bigint,
  debit numeric,
  credit numeric,
  created_at timestamptz DEFAULT now()
);

-- Employee & Payroll
CREATE TABLE IF NOT EXISTS "Employee" (
  id bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  company_id bigint,
  name text,
  designation text,
  department text,
  joining_date date,
  basic_salary numeric,
  created_at timestamptz DEFAULT now()
);

CREATE TABLE IF NOT EXISTS "SalaryComponent" (
  id bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  company_id bigint,
  name text,
  type text, -- 'Earning' or 'Deduction'
  created_at timestamptz DEFAULT now()
);

CREATE TABLE IF NOT EXISTS "Payroll" (
  id bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  company_id bigint,
  employee_id bigint,
  month text,
  year int,
  total_earnings numeric,
  total_deductions numeric,
  net_salary numeric,
  created_at timestamptz DEFAULT now()
);

CREATE TABLE IF NOT EXISTS "EmployeeSalaryStrucure" (
  id bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  employee_id bigint,
  component_id bigint,
  amount numeric,
  created_at timestamptz DEFAULT now()
);

-- Other modules
CREATE TABLE IF NOT EXISTS "CustodyWallet" (
  id bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  company_id bigint,
  employee_id bigint,
  balance numeric,
  created_at timestamptz DEFAULT now()
);

CREATE TABLE IF NOT EXISTS "CustodyTransaction" (
  id bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  wallet_id bigint,
  amount numeric,
  type text, -- 'Credit' or 'Debit'
  description text,
  date timestamptz,
  created_at timestamptz DEFAULT now()
);

CREATE TABLE IF NOT EXISTS "FlowerWaste" (
  id bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  company_id bigint,
  date date,
  item_name text,
  quantity numeric,
  reason text,
  created_at timestamptz DEFAULT now()
);

CREATE TABLE IF NOT EXISTS "BankReconciliation" (
  id bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  company_id bigint,
  ledger_id bigint,
  bank_date date,
  amount numeric,
  created_at timestamptz DEFAULT now()
);

CREATE TABLE IF NOT EXISTS "ZATCAInvoice" (
  id bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  voucher_id bigint,
  zatca_uuid text,
  hash text,
  status text,
  created_at timestamptz DEFAULT now()
);

CREATE TABLE IF NOT EXISTS "BranchDailyRecord" (
  id bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  branch_id bigint,
  date date,
  data jsonb, -- Store complex daily record data as JSON
  created_at timestamptz DEFAULT now()
);

-- Row Level Security (RLS) - Optional but recommended
-- ALTER TABLE "Company" ENABLE ROW LEVEL SECURITY;
-- (Add policies as needed)
