-- Subscription Keys Management
-- Run this in Supabase SQL Editor

-- 1. Create Table
CREATE TABLE IF NOT EXISTS "subscription_keys" (
  id bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  key_code text UNIQUE NOT NULL,
  plan_type text NOT NULL DEFAULT 'premium', -- 'premium'
  status text NOT NULL DEFAULT 'active', -- 'active', 'used', 'revoked'
  claimed_by uuid REFERENCES auth.users(id),
  claimed_at timestamptz,
  created_at timestamptz DEFAULT now()
);

-- 2. Enable RLS
ALTER TABLE "subscription_keys" ENABLE ROW LEVEL SECURITY;

-- 3. RLS Policies

-- Allow users to see keys they have claimed
CREATE POLICY "Users can view own keys" ON "subscription_keys"
  FOR SELECT
  USING (claimed_by = auth.uid());

-- Allow admins (service role or specific email) to do everything
-- Note: You can adjust this policy based on your admin role logic
CREATE POLICY "Admins full access" ON "subscription_keys"
  FOR ALL
  USING (
    -- Simple check: if the user has a specific email (update this!)
    auth.jwt() ->> 'email' = 'admin@example.com' 
    OR 
    -- Or if you use the 'service_role' key
    auth.role() = 'service_role'
  );

-- 4. Secure Function to Claim Key (Prevents race conditions)
CREATE OR REPLACE FUNCTION claim_subscription_key(input_key text)
RETURNS json
LANGUAGE plpgsql
SECURITY DEFINER -- Runs with privileges of the creator (admin)
AS $$
DECLARE
  key_record record;
  user_id uuid;
  user_email text;
BEGIN
  -- Get current user
  user_id := auth.uid();
  user_email := auth.jwt() ->> 'email';
  
  IF user_id IS NULL THEN
    RETURN json_build_object('success', false, 'message', 'User not authenticated');
  END IF;

  -- Find the key (must be active)
  SELECT * INTO key_record FROM "subscription_keys" 
  WHERE key_code = input_key AND status = 'active'
  FOR UPDATE; -- Lock the row to prevent double claiming

  IF key_record.id IS NULL THEN
     RETURN json_build_object('success', false, 'message', 'Invalid or expired key');
  END IF;

  -- Mark as used
  UPDATE "subscription_keys"
  SET 
    status = 'used',
    claimed_by = user_id,
    claimed_at = now()
  WHERE id = key_record.id;

  -- Log/Audit (Optional)
  -- RAISE NOTICE 'User % claimed key %', user_email, input_key;

  RETURN json_build_object('success', true, 'message', 'Key activated successfully', 'plan', key_record.plan_type);
END;
$$;

-- 5. Insert some initial keys for testing (Optional)
INSERT INTO "subscription_keys" (key_code, plan_type)
VALUES 
  ('RCAS-PRO-2024', 'premium'),
  ('PREMIUM-KEY-123', 'premium'),
  ('RCAS-LIFETIME', 'premium')
ON CONFLICT (key_code) DO NOTHING;
