import React, { useState, useEffect } from 'react';
import { rcas } from '@/api/rcasClient';
import { useQuery, useMutation, useQueryClient } from '@tanstack/react-query';
import { useCurrency } from '@/context/CurrencyContext';
import { useAuth, ROLES } from '@/context/AuthContext';
import { useTheme } from '@/context/ThemeContext';
import { useSubscription, SUBSCRIPTION_PLANS, FEATURE_LIMITS } from '@/context/SubscriptionContext';
import { useConfirm } from '@/context/ConfirmContext';
import { formatCurrency } from '@/utils';
import PageHeader from '@/components/common/PageHeader';
import FormField from '@/components/forms/FormField';
import LoadingSpinner from '@/components/common/LoadingSpinner';
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Badge } from "@/components/ui/badge";
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from "@/components/ui/card";
import { Switch } from "@/components/ui/switch";
import { Label } from "@/components/ui/label";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { toast } from "sonner";
import { 
  Settings, Save, Database, FileText, Calculator, Globe, 
  Building2, Receipt, ShieldCheck, Printer, Lock, KeyRound,
  Download, Upload, Cloud, HardDrive, Palette, Moon, Sun, Monitor,
  CreditCard, Check, X, Crown
} from 'lucide-react';

export default function AppSettings() {
  const queryClient = useQueryClient();
  const { confirm } = useConfirm();
  const { user, hasRole } = useAuth();
  const { plan, upgradeToPremium, downgradeToFree, activateProduct, buyPremium, removeProduct, productId } = useSubscription();
  const [productKeyInput, setProductKeyInput] = useState('');
  const [isProcessingPayment, setIsProcessingPayment] = useState(false);

  const handleActivateProduct = async () => {
    if (await activateProduct(productKeyInput)) {
      setProductKeyInput('');
    }
  };

  const handleBuyPremium = async () => {
    setIsProcessingPayment(true);
    const result = await buyPremium();
    setIsProcessingPayment(false);
    
    if (result.success) {
      toast.success("Payment Successful!", {
        description: `Your Product Key: ${result.key} (Auto-activated)`
      });
    }
  };

  const currentPlan = {
    id: plan,
    name: plan === SUBSCRIPTION_PLANS.PREMIUM ? 'Premium Plan' : 'Free Plan',
    price: plan === SUBSCRIPTION_PLANS.PREMIUM ? 49 : 0
  };
  const { theme, setTheme, colorTheme, setColorTheme } = useTheme();
  const { baseCurrency, baseCurrencySymbol, setSelectedCurrency, CURRENCY_SYMBOLS } = useCurrency();
  const [activeTab, setActiveTab] = useState('appearance');
  
  // Change Password State
  const [passwordData, setPasswordData] = useState({ current: '', new: '', confirm: '' });

  const defaultSettings = {
    // Company Info
    company_name: '',
    company_address: '',
    company_phone: '',
    company_email: '',
    company_website: '',
    vat_number: '', // TRN
    commercial_registration: '', // CR Number
    logo_url: '',

    // Accounting & Currency
    base_currency: 'SAR',
    currency_symbol: '﷼',
    decimal_places: '2',
    date_format: 'dd/MM/yyyy',
    fiscal_year_start: '01',
    vat_rate: '15',
    
    // Inventory
    enable_inventory: true,
    enable_negative_stock: false,
    valuation_method: 'FIFO',
    enable_batches: false,
    enable_expiry: false,

    // Vouchers & Prefixes
    auto_voucher_numbering: true,
    invoice_prefix: 'INV',
    purchase_prefix: 'PUR',
    receipt_prefix: 'REC',
    payment_prefix: 'PAY',
    journal_prefix: 'JNL',
    
    // Modules & Features
    enable_payroll: true,
    enable_cost_centers: false,
    require_narration: false,
    
    // Print Settings
    invoice_terms: 'Payment is due within 30 days.\nThank you for your business.',
    invoice_footer: 'Generated by RCAS System'
  };

  const [settings, setSettings] = useState(defaultSettings);
  const [settingsId, setSettingsId] = useState(null);

  // Load Settings
  const { data: existingSettings, isLoading } = useQuery({
    queryKey: ['settings'],
    queryFn: async () => {
      const list = await rcas.entities.Settings.list();
      return list.length > 0 ? list[0] : null;
    }
  });

  useEffect(() => {
    if (existingSettings) {
      setSettings(prev => ({ ...prev, ...existingSettings }));
      setSettingsId(existingSettings.id);
      
      // Sync currency context if needed
      if (existingSettings.base_currency && existingSettings.base_currency !== baseCurrency) {
        setSelectedCurrency(existingSettings.base_currency, existingSettings.currency_symbol || CURRENCY_SYMBOLS[existingSettings.base_currency]);
      }
    }
  }, [existingSettings, baseCurrency, setSelectedCurrency, CURRENCY_SYMBOLS]);

  const saveMutation = useMutation({
    mutationFn: async (newSettings) => {
      if (settingsId) {
        return rcas.entities.Settings.update(settingsId, newSettings);
      } else {
        return rcas.entities.Settings.create(newSettings);
      }
    },
    onSuccess: (data) => {
      setSettingsId(data.id);
      queryClient.invalidateQueries(['settings']);
      toast.success('Settings saved successfully');
      
      // Update global context
      setSelectedCurrency(settings.base_currency, settings.currency_symbol);
    },
    onError: () => {
      toast.error('Failed to save settings');
    }
  });

  const handleChange = (field, value) => {
    setSettings(prev => ({ ...prev, [field]: value }));
  };

  const handleSave = () => {
    console.log("Saving settings...", settings);
    saveMutation.mutate(settings);
  };

  const handleChangePassword = async (e) => {
    e.preventDefault();
    if (passwordData.new !== passwordData.confirm) {
      toast.error("New passwords do not match");
      return;
    }
    
    try {
      // Update user password via API
      await rcas.entities.User.update(user.id, { password: passwordData.new });
      
      toast.success("Password updated successfully");
      setPasswordData({ current: '', new: '', confirm: '' });
    } catch (error) {
      console.error(error);
      toast.error("Failed to update password");
    }
  };

  const [dbConfig, setDbConfig] = useState({
    provider: 'local_storage',
    supabaseUrl: '',
    supabaseKey: '',
    apiKey: '',
    projectId: '',
    apiUrl: ''
  });

  useEffect(() => {
    const savedConfig = localStorage.getItem('rcas_db_config');
    if (savedConfig) {
      setDbConfig(JSON.parse(savedConfig));
    } else {
      // Auto-detect from Env Vars (Supabase)
      const envSupabaseUrl = import.meta.env.VITE_SUPABASE_URL;
      const envSupabaseKey = import.meta.env.VITE_SUPABASE_KEY || import.meta.env.VITE_SUPABASE_ANON_KEY;
      if (envSupabaseUrl && envSupabaseKey) {
        setDbConfig(prev => ({
          ...prev,
          provider: 'supabase',
          supabaseUrl: envSupabaseUrl,
          supabaseKey: envSupabaseKey
        }));
      }
    }
  }, []);

  const handleDbSave = async (e) => {
    e.preventDefault();
    try {
      await rcas.configure(dbConfig);
      toast.success("Database configuration updated. App will reload.");
      setTimeout(() => window.location.reload(), 1500);
    } catch (error) {
      toast.error("Failed to update database config");
    }
  };

  // --- Data Backup & Restore ---
  const [isExporting, setIsExporting] = useState(false);
  const [isImporting, setIsImporting] = useState(false);

  const handleExportData = async () => {
    setIsExporting(true);
    try {
      const timestamp = new Date().toISOString().replace(/[:.]/g, '-');
      const backupData = {
        meta: {
          version: '1.0',
          timestamp: new Date().toISOString(),
          provider: rcas.getProvider()
        },
        data: {}
      };

      // Fetch all entities
      const entities = Object.keys(rcas.entities);
      for (const entityName of entities) {
        // Skip IDCounter or internal tables if needed, but usually safe to backup all
        const records = await rcas.entities[entityName].list();
        backupData.data[entityName] = records;
      }

      // Create and download file
      const blob = new Blob([JSON.stringify(backupData, null, 2)], { type: 'application/json' });
      const url = URL.createObjectURL(blob);
      const link = document.createElement('a');
      link.href = url;
      link.download = `rcas_backup_${timestamp}.json`;
      document.body.appendChild(link);
      link.click();
      document.body.removeChild(link);
      
      toast.success(`Backup created successfully with ${Object.keys(backupData.data).length} entities.`);
    } catch (error) {
      console.error("Export failed:", error);
      toast.error("Failed to export data. See console for details.");
    } finally {
      setIsExporting(false);
    }
  };

  const handleImportData = async (event) => {
    const file = event.target.files[0];
    if (!file) return;

    if (!await confirm({
      title: 'Import Data Warning',
      description: "Importing data will merge with existing records. IDs might conflict. Ideally, do this on a fresh/empty database. Continue?",
      variant: 'destructive',
      confirmText: 'Import Data'
    })) {
      event.target.value = ''; // Reset input
      return;
    }

    setIsImporting(true);
    try {
      const reader = new FileReader();
      reader.onload = async (e) => {
        try {
          const backup = JSON.parse(e.target.result);
          if (!backup.data) throw new Error("Invalid backup file format");

          let successCount = 0;
          let errorCount = 0;

          // Process each entity
          for (const [entityName, records] of Object.entries(backup.data)) {
            if (!rcas.entities[entityName]) continue;

            for (const record of records) {
              try {
                // Try to create. If ID exists, it might fail depending on adapter.
                // For LocalStorage, create() usually overwrites if ID is same? 
                // Let's check adapter logic or just try.
                // If it fails, we might want to try update() or just skip.
                // Safest is to try create, catch error.
                
                // Remove internal fields if any?
                // Usually adapters handle ID.
                await rcas.entities[entityName].create(record);
                successCount++;
              } catch (err) {
                // If create fails, maybe ID exists. Try update?
                try {
                  if (record.id) {
                     await rcas.entities[entityName].update(record.id, record);
                     successCount++;
                  } else {
                    errorCount++;
                  }
                } catch (updateErr) {
                  errorCount++;
                }
              }
            }
          }

          toast.success(`Import complete. Processed: ${successCount}, Skipped/Failed: ${errorCount}`);
          queryClient.invalidateQueries(); // Refresh UI
          
        } catch (parseError) {
          console.error(parseError);
          toast.error("Failed to parse backup file");
        } finally {
          setIsImporting(false);
          event.target.value = ''; // Reset
        }
      };
      reader.readAsText(file);
    } catch (error) {
      console.error(error);
      toast.error("Import failed");
      setIsImporting(false);
    }
  };

  if (isLoading) return <LoadingSpinner />;

  return (
    <div className="max-w-5xl mx-auto pb-10">
      <PageHeader 
        title="App Settings" 
        subtitle="Configure system preferences, company details, and modules" 
        icon={Settings}
      />

      <Tabs value={activeTab} onValueChange={setActiveTab} className="space-y-6">
        <TabsList className="flex flex-wrap justify-center h-auto w-full gap-1 bg-muted p-1">
          <TabsTrigger 
            value="appearance" 
            className="flex-1 min-w-[100px] py-3"
          >
            Appearance
          </TabsTrigger>
          <TabsTrigger 
            value="security" 
            className="flex-1 min-w-[100px] py-3"
          >
            Security
          </TabsTrigger>
          <TabsTrigger 
            value="database" 
            className="flex-1 min-w-[100px] py-3"
          >
            Database
          </TabsTrigger>
          <TabsTrigger 
            value="data" 
            className="flex-1 min-w-[100px] py-3"
          >
            Backup & Data
          </TabsTrigger>
          <TabsTrigger 
            value="subscription" 
            className="flex-1 min-w-[100px] py-3"
          >
            Subscription
          </TabsTrigger>
          {/* Subscription Settings */}
        <TabsContent value="subscription">
          <Card>
            <CardHeader>
              <CardTitle className="flex items-center gap-2">
                <CreditCard className="h-5 w-5 text-purple-600" />
                Subscription & Billing
              </CardTitle>
              <CardDescription>Manage your subscription plan and billing details</CardDescription>
            </CardHeader>
            <CardContent className="space-y-6">
              {/* Product Key Activation */}
              <div className="p-4 border rounded-lg bg-slate-50 dark:bg-slate-900/50 space-y-4">
                 <div className="flex flex-col gap-2">
                    <Label>Have a Product Key?</Label>
                    <div className="flex gap-2">
                        <Input 
                          placeholder="Enter your Product ID (e.g. RCAS-PRO-2024)" 
                          value={productKeyInput}
                          onChange={(e) => setProductKeyInput(e.target.value)}
                          className="max-w-md"
                        />
                        <Button onClick={handleActivateProduct}>Activate</Button>
                    </div>
                    <p className="text-xs text-slate-500">
                      Enter a valid subscription product ID to unlock Premium features.
                    </p>
                 </div>
                 {productId && (
                    <div className="flex items-center justify-between bg-emerald-50 dark:bg-emerald-900/20 p-3 rounded border border-emerald-200 dark:border-emerald-900">
                        <span className="text-sm text-emerald-700 dark:text-emerald-400 font-medium flex items-center gap-2">
                            <Check className="h-4 w-4" />
                            Active License: {productId}
                        </span>
                        <Button variant="ghost" size="sm" onClick={removeProduct} className="text-red-500 hover:text-red-600 hover:bg-red-50 dark:hover:bg-red-900/20">
                            Remove
                        </Button>
                    </div>
                 )}
              </div>

              {/* Current Plan Status */}
              <div className="flex items-center justify-between p-4 border rounded-lg bg-slate-50 dark:bg-slate-900/50">
                <div className="space-y-1">
                  <p className="text-sm font-medium text-slate-500">Current Plan</p>
                  <div className="flex items-center gap-2">
                    <span className="text-2xl font-bold">{currentPlan.name}</span>
                    {currentPlan.id === SUBSCRIPTION_PLANS.PREMIUM && (
                      <Badge className="bg-amber-500 hover:bg-amber-600">
                        <Crown className="h-3 w-3 mr-1" /> PRO
                      </Badge>
                    )}
                  </div>
                  <p className="text-sm text-slate-500">
                    {currentPlan.id === SUBSCRIPTION_PLANS.FREE 
                      ? "Basic access to all features with monthly limits." 
                      : "Unlimited access to all features and advanced reports."}
                  </p>
                </div>
                <div className="text-right">
                  <p className="text-sm font-medium text-slate-500">Price</p>
                  <p className="text-2xl font-bold">{formatCurrency(currentPlan.price, 'USD')}<span className="text-sm font-normal text-slate-500">/mo</span></p>
                </div>
              </div>

              {/* Plan Comparison / Features */}
              <div className="grid md:grid-cols-2 gap-6">
                 {/* Free Plan Details */}
                 <div className={`p-6 rounded-xl border-2 ${currentPlan.id === SUBSCRIPTION_PLANS.FREE ? 'border-primary bg-primary/5' : 'border-slate-100 dark:border-slate-800'}`}>
                    <div className="flex justify-between items-start mb-4">
                      <div>
                        <h3 className="font-bold text-lg">Free Tier</h3>
                        <p className="text-slate-500 text-sm">For individuals and small tests</p>
                      </div>
                      {currentPlan.id === SUBSCRIPTION_PLANS.FREE && <Badge variant="outline" className="border-primary text-primary">Current</Badge>}
                    </div>
                    <ul className="space-y-3 mb-6">
                      <li className="flex items-center gap-2 text-sm"><Check className="h-4 w-4 text-emerald-500" /> {FEATURE_LIMITS.waste_tracker.max_entries_per_month} Waste Entries/mo</li>
                      <li className="flex items-center gap-2 text-sm"><Check className="h-4 w-4 text-emerald-500" /> {FEATURE_LIMITS.custody_wallet.max_wallets} Custody Wallet</li>
                      <li className="flex items-center gap-2 text-sm"><Check className="h-4 w-4 text-emerald-500" /> {FEATURE_LIMITS.custody_wallet.max_transactions_per_month} Wallet Transactions/mo</li>
                      <li className="flex items-center gap-2 text-sm"><Check className="h-4 w-4 text-emerald-500" /> {FEATURE_LIMITS.supplier_comparison.max_suppliers} Supplier Comparisons</li>
                      <li className="flex items-center gap-2 text-sm text-slate-400"><X className="h-4 w-4" /> No Export / Reports</li>
                      <li className="flex items-center gap-2 text-sm text-slate-400"><X className="h-4 w-4" /> Ad-supported</li>
                    </ul>
                    {currentPlan.id !== SUBSCRIPTION_PLANS.FREE && (
                      <Button variant="outline" className="w-full" onClick={() => downgradeToFree()}>Downgrade to Free</Button>
                    )}
                 </div>

                 {/* Premium Plan Details */}
                 <div className={`p-6 rounded-xl border-2 ${currentPlan.id === SUBSCRIPTION_PLANS.PREMIUM ? 'border-amber-500 bg-amber-50 dark:bg-amber-900/10' : 'border-slate-100 dark:border-slate-800'}`}>
                    <div className="flex justify-between items-start mb-4">
                      <div>
                        <h3 className="font-bold text-lg flex items-center gap-2">Premium <Crown className="h-4 w-4 text-amber-500" /></h3>
                        <p className="text-slate-500 text-sm">For growing businesses</p>
                      </div>
                      {currentPlan.id === SUBSCRIPTION_PLANS.PREMIUM && <Badge className="bg-amber-500 hover:bg-amber-600">Current</Badge>}
                    </div>
                    <ul className="space-y-3 mb-6">
                      <li className="flex items-center gap-2 text-sm"><Check className="h-4 w-4 text-emerald-500" /> Unlimited Waste Entries</li>
                      <li className="flex items-center gap-2 text-sm"><Check className="h-4 w-4 text-emerald-500" /> Unlimited Custody Wallets</li>
                      <li className="flex items-center gap-2 text-sm"><Check className="h-4 w-4 text-emerald-500" /> Unlimited Transactions</li>
                      <li className="flex items-center gap-2 text-sm"><Check className="h-4 w-4 text-emerald-500" /> Full Supplier Comparison</li>
                      <li className="flex items-center gap-2 text-sm"><Check className="h-4 w-4 text-emerald-500" /> CSV/PDF Exports</li>
                      <li className="flex items-center gap-2 text-sm"><Check className="h-4 w-4 text-emerald-500" /> No Ads</li>
                    </ul>
                    {currentPlan.id !== SUBSCRIPTION_PLANS.PREMIUM && (
                      <Button 
                        className="w-full bg-gradient-to-r from-amber-500 to-orange-600 hover:from-amber-600 hover:to-orange-700 text-white border-0" 
                        onClick={handleBuyPremium}
                        disabled={isProcessingPayment}
                      >
                        {isProcessingPayment ? <LoadingSpinner size="sm" /> : 'Buy Premium ($49)'}
                      </Button>
                    )}
                 </div>
              </div>
            </CardContent>
          </Card>
        </TabsContent>

        {hasRole([ROLES.SUPER_ADMIN]) && (
            <>
              <TabsTrigger 
                value="company" 
                className="flex-1 min-w-[100px] py-3"
              >
                Company
              </TabsTrigger>
              <TabsTrigger 
                value="accounting" 
                className="flex-1 min-w-[100px] py-3"
              >
                Accounting
              </TabsTrigger>
              <TabsTrigger 
                value="inventory" 
                className="flex-1 min-w-[100px] py-3"
              >
                Inventory
              </TabsTrigger>
              <TabsTrigger 
                value="vouchers" 
                className="flex-1 min-w-[100px] py-3"
              >
                Vouchers
              </TabsTrigger>
              <TabsTrigger 
                value="system" 
                className="flex-1 min-w-[100px] py-3"
              >
                System
              </TabsTrigger>
            </>
          )}
        </TabsList>

        {/* Appearance Settings */}
        <TabsContent value="appearance">
          <div className="grid gap-6">
            <Card>
              <CardHeader>
                <CardTitle className="flex items-center gap-2">
                  <Palette className="h-5 w-5 text-primary" />
                  Theme Customization
                </CardTitle>
                <CardDescription>Customize the look and feel of the application</CardDescription>
              </CardHeader>
              <CardContent className="space-y-8">
                {/* Mode Selection */}
                <div className="space-y-4">
                  <h3 className="text-sm font-medium text-slate-700 dark:text-slate-300">Interface Mode</h3>
                  <div className="grid grid-cols-3 gap-4">
                    <button
                      onClick={() => setTheme('light')}
                      className={`flex flex-col items-center justify-center p-4 rounded-xl border-2 transition-all ${
                        theme === 'light' 
                          ? 'border-primary bg-primary/5 text-primary' 
                          : 'border-slate-200 dark:border-slate-800 hover:border-slate-300 dark:hover:border-slate-700'
                      }`}
                    >
                      <Sun className="h-6 w-6 mb-2" />
                      <span className="text-sm font-medium">Light</span>
                    </button>
                    <button
                      onClick={() => setTheme('dark')}
                      className={`flex flex-col items-center justify-center p-4 rounded-xl border-2 transition-all ${
                        theme === 'dark' 
                          ? 'border-primary bg-primary/5 text-primary' 
                          : 'border-slate-200 dark:border-slate-800 hover:border-slate-300 dark:hover:border-slate-700'
                      }`}
                    >
                      <Moon className="h-6 w-6 mb-2" />
                      <span className="text-sm font-medium">Dark</span>
                    </button>
                    <button
                      onClick={() => setTheme('system')}
                      className={`flex flex-col items-center justify-center p-4 rounded-xl border-2 transition-all ${
                        theme === 'system' 
                          ? 'border-primary bg-primary/5 text-primary' 
                          : 'border-slate-200 dark:border-slate-800 hover:border-slate-300 dark:hover:border-slate-700'
                      }`}
                    >
                      <Monitor className="h-6 w-6 mb-2" />
                      <span className="text-sm font-medium">System</span>
                    </button>
                  </div>
                </div>

                {/* Color Theme Selection */}
                <div className="space-y-4">
                  <h3 className="text-sm font-medium text-slate-700 dark:text-slate-300">Accent Color</h3>
                  <div className="grid grid-cols-2 md:grid-cols-5 gap-4">
                    {[
                      { id: 'emerald', name: 'Emerald', color: 'bg-emerald-500' },
                      { id: 'blue', name: 'Blue', color: 'bg-blue-500' },
                      { id: 'purple', name: 'Purple', color: 'bg-purple-500' },
                      { id: 'rose', name: 'Rose', color: 'bg-rose-500' },
                      { id: 'orange', name: 'Orange', color: 'bg-orange-500' }
                    ].map((color) => (
                      <button
                        key={color.id}
                        onClick={() => setColorTheme(color.id)}
                        className={`group relative flex items-center gap-3 p-3 rounded-xl border-2 transition-all ${
                          colorTheme === color.id 
                            ? 'border-primary bg-primary/5' 
                            : 'border-slate-200 dark:border-slate-800 hover:border-slate-300 dark:hover:border-slate-700'
                        }`}
                      >
                        <div className={`h-6 w-6 rounded-full ${color.color} shadow-sm`} />
                        <span className={`text-sm font-medium ${
                          colorTheme === color.id ? 'text-primary' : 'text-slate-600 dark:text-slate-400'
                        }`}>
                          {color.name}
                        </span>
                      </button>
                    ))}
                  </div>
                </div>
              </CardContent>
            </Card>
          </div>
        </TabsContent>

        {/* Security Settings */}
        <TabsContent value="security">
          <Card>
            <CardHeader>
              <CardTitle className="flex items-center gap-2">
                <Lock className="h-5 w-5 text-emerald-600" />
                Account Security
              </CardTitle>
              <CardDescription>Manage your password and account security settings</CardDescription>
            </CardHeader>
            <CardContent>
              <form onSubmit={handleChangePassword} className="space-y-4 max-w-md">
                <FormField 
                  label="Current Password" 
                  type="password" 
                  value={passwordData.current} 
                  onChange={(e) => setPasswordData({...passwordData, current: e.target.value})} 
                  required 
                />
                <FormField 
                  label="New Password" 
                  type="password" 
                  value={passwordData.new} 
                  onChange={(e) => setPasswordData({...passwordData, new: e.target.value})} 
                  required 
                />
                <FormField 
                  label="Confirm New Password" 
                  type="password" 
                  value={passwordData.confirm} 
                  onChange={(e) => setPasswordData({...passwordData, confirm: e.target.value})} 
                  required 
                />
                <Button type="submit">Update Password</Button>
              </form>
            </CardContent>
          </Card>
        </TabsContent>

        {/* Database Settings */}
        <TabsContent value="database">
          <Card>
            <CardHeader>
              <CardTitle className="flex items-center gap-2">
                <Database className="h-5 w-5 text-blue-600" />
                Database Connection
              </CardTitle>
              <CardDescription>Connect your application to a backend database</CardDescription>
            </CardHeader>
            <CardContent>
              <form onSubmit={handleDbSave} className="space-y-6 max-w-xl">
                <FormField
                  label="Database Provider"
                  type="select"
                  value={dbConfig.provider}
                  onChange={(e) => setDbConfig({...dbConfig, provider: e.target.value})}
                  options={[
                    { value: 'local_storage', label: 'Local Storage (Browser Only)' },
                    { value: 'insforge', label: 'InsForge (Managed Backend)' },
                    { value: 'supabase', label: 'Supabase (PostgreSQL)' },
                    { value: 'firebase', label: 'Firebase (Firestore)' },
                    { value: 'rest_api', label: 'Custom REST API (MySQL/MSSQL/Mongo via Backend)' }
                  ]}
                  description="Choose where your data is stored. Changing this will reload the application."
                />

                {dbConfig.provider === 'insforge' && (
                  <div className="space-y-4 border p-4 rounded-lg bg-slate-50 dark:bg-slate-900/50 dark:border-slate-800">
                    <FormField
                      label="InsForge Base URL"
                      value={dbConfig.baseUrl}
                      onChange={(e) => setDbConfig({...dbConfig, baseUrl: e.target.value})}
                      placeholder="https://your-app.region.insforge.app"
                    />
                    <FormField
                      label="Anon Key"
                      value={dbConfig.anonKey}
                      onChange={(e) => setDbConfig({...dbConfig, anonKey: e.target.value})}
                      type="password"
                      placeholder="public-anon-key"
                    />
                    <p className="text-xs text-slate-500">
                      You can find these details in your InsForge project settings.
                    </p>
                  </div>
                )}

                {dbConfig.provider === 'supabase' && (
                  <div className="space-y-4 border p-4 rounded-lg bg-slate-50 dark:bg-slate-900/50 dark:border-slate-800">
                    <FormField
                      label="Supabase URL"
                      value={dbConfig.supabaseUrl}
                      onChange={(e) => setDbConfig({...dbConfig, supabaseUrl: e.target.value})}
                      placeholder="https://your-project.supabase.co"
                      required
                    />
                    <FormField
                      label="Supabase Anon Key"
                      value={dbConfig.supabaseKey}
                      onChange={(e) => setDbConfig({...dbConfig, supabaseKey: e.target.value})}
                      type="password"
                      placeholder="your-anon-key"
                      required
                    />
                    <div className="text-sm text-slate-500">
                      You need to create tables in Supabase matching the entity names (e.g., Company, Voucher, etc.) or use the SQL setup script.
                    </div>
                  </div>
                )}

                {dbConfig.provider === 'firebase' && (
                  <div className="space-y-4 border p-4 rounded-lg bg-slate-50 dark:bg-slate-900/50 dark:border-slate-800">
                    <FormField
                      label="Firebase API Key"
                      value={dbConfig.apiKey}
                      onChange={(e) => setDbConfig({...dbConfig, apiKey: e.target.value})}
                      type="password"
                      required
                    />
                    <FormField
                      label="Project ID"
                      value={dbConfig.projectId}
                      onChange={(e) => setDbConfig({...dbConfig, projectId: e.target.value})}
                      required
                    />
                    <div className="text-sm text-slate-500">
                      Ensure Firestore Database is enabled in your Firebase Console.
                    </div>
                  </div>
                )}

                {dbConfig.provider === 'rest_api' && (
                  <div className="space-y-4 border p-4 rounded-lg bg-slate-50 dark:bg-slate-900/50 dark:border-slate-800">
                    <FormField
                      label="API Base URL"
                      value={dbConfig.apiUrl}
                      onChange={(e) => setDbConfig({...dbConfig, apiUrl: e.target.value})}
                      placeholder="https://api.yourdomain.com/v1"
                      required
                    />
                    <FormField
                      label="API Key / Token"
                      value={dbConfig.apiKey}
                      onChange={(e) => setDbConfig({...dbConfig, apiKey: e.target.value})}
                      type="password"
                      placeholder="Optional API Key"
                    />
                    <div className="text-sm text-slate-500">
                      Use this to connect to a backend server running PostgreSQL, MySQL, MSSQL, or MongoDB.
                    </div>
                  </div>
                )}

                <Button type="submit" className="w-full">
                  <Save className="mr-2 h-4 w-4" />
                  Save & Reload
                </Button>
              </form>
            </CardContent>
          </Card>
        </TabsContent>

        {/* Data Backup & Restore */}
        <TabsContent value="data">
          <div className="grid gap-6">
            <Card>
              <CardHeader>
                <CardTitle className="flex items-center gap-2">
                  <HardDrive className="h-5 w-5 text-orange-600" />
                  Local Backup (Device)
                </CardTitle>
                <CardDescription>Save a copy of your data to your computer or restore from a file.</CardDescription>
              </CardHeader>
              <CardContent className="space-y-4">
                <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
                  <div className="border rounded-lg p-4 bg-slate-50 space-y-3">
                    <div className="flex items-center gap-2 font-semibold text-slate-700">
                      <Download className="h-4 w-4" />
                      Export Data
                    </div>
                    <p className="text-sm text-slate-500">
                      Download all your data (Company, Vouchers, Inventory, etc.) as a JSON file. 
                      Keep this file safe.
                    </p>
                    <Button onClick={handleExportData} disabled={isExporting} className="w-full" variant="outline">
                      {isExporting ? <LoadingSpinner size="sm" /> : <><Download className="mr-2 h-4 w-4" /> Download Backup</>}
                    </Button>
                  </div>

                  <div className="border rounded-lg p-4 bg-slate-50 space-y-3">
                    <div className="flex items-center gap-2 font-semibold text-slate-700">
                      <Upload className="h-4 w-4" />
                      Import / Restore
                    </div>
                    <p className="text-sm text-slate-500">
                      Restore data from a backup file. 
                      <span className="text-red-500 font-bold block mt-1">⚠️ This will merge/overwrite data!</span>
                    </p>
                    <div className="relative">
                      <Button disabled={isImporting} className="w-full" variant="outline">
                        {isImporting ? <LoadingSpinner size="sm" /> : <><Upload className="mr-2 h-4 w-4" /> Select Backup File</>}
                      </Button>
                      <input 
                        type="file" 
                        accept=".json" 
                        onChange={handleImportData}
                        className="absolute inset-0 opacity-0 cursor-pointer"
                        disabled={isImporting}
                      />
                    </div>
                  </div>
                </div>
              </CardContent>
            </Card>

            <Card>
              <CardHeader>
                <CardTitle className="flex items-center gap-2">
                  <Cloud className="h-5 w-5 text-blue-600" />
                  Online / Cloud Sync
                </CardTitle>
                <CardDescription>Manage your connection to online databases.</CardDescription>
              </CardHeader>
              <CardContent className="space-y-4">
                <div className="flex items-center justify-between p-4 border rounded-lg">
                  <div>
                    <p className="font-semibold">Current Provider</p>
                    <p className="text-sm text-slate-500">
                      {dbConfig.provider === 'local_storage' ? 'Local Storage (Offline)' : 
                       dbConfig.provider === 'supabase' ? 'Supabase (Cloud)' : 
                       dbConfig.provider === 'firebase' ? 'Firebase (Cloud)' : 'Custom API'}
                    </p>
                  </div>
                  <div className="flex items-center gap-2">
                    {dbConfig.provider === 'local_storage' ? (
                      <span className="px-2 py-1 bg-yellow-100 text-yellow-800 text-xs font-bold rounded">OFFLINE</span>
                    ) : (
                      <span className="px-2 py-1 bg-green-100 text-green-800 text-xs font-bold rounded">ONLINE</span>
                    )}
                  </div>
                </div>

                {dbConfig.provider === 'local_storage' && (
                  <div className="bg-blue-50 border border-blue-100 rounded-lg p-4 text-sm text-blue-800">
                    <p className="font-bold mb-2">💡 Want to access your data from multiple devices?</p>
                    <p className="mb-2">
                      Switch to an <strong>Online Provider</strong> (Supabase or Firebase) in the <span className="font-mono bg-white dark:bg-slate-900 px-1 rounded">Database</span> tab.
                    </p>
                    <p>
                      <strong>How to migrate:</strong>
                      <ol className="list-decimal ml-4 mt-1 space-y-1">
                        <li>Download a Backup (Export) from above.</li>
                        <li>Go to <strong>Database</strong> tab and connect to Supabase/Firebase.</li>
                        <li>The app will reload in "Online Mode".</li>
                        <li>Come back here and <strong>Import</strong> your backup file.</li>
                      </ol>
                    </p>
                  </div>
                )}

                {dbConfig.provider !== 'local_storage' && (
                  <div className="bg-green-50 border border-green-100 rounded-lg p-4 text-sm text-green-800">
                    <p className="font-bold">✅ You are connected to the Cloud!</p>
                    <p>Your data is automatically synced to the database. You can log in from any device to access it.</p>
                  </div>
                )}
              </CardContent>
            </Card>
          </div>
        </TabsContent>

        {hasRole([ROLES.SUPER_ADMIN]) && (
          <>
        {/* Company Settings */}
        <TabsContent value="company">
          <Card>
            <CardHeader>
              <CardTitle className="flex items-center gap-2">
                <Building2 className="h-5 w-5 text-emerald-600" />
                Company Information
              </CardTitle>
              <CardDescription>Details that appear on your invoices and reports</CardDescription>
            </CardHeader>
            <CardContent className="space-y-4">
              <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                <FormField label="Company Name" value={settings.company_name} onChange={(e) => handleChange('company_name', e.target.value)} placeholder="e.g. Al-Rustam Trading Co." />
                <FormField label="Email Address" value={settings.company_email} onChange={(e) => handleChange('company_email', e.target.value)} type="email" />
                <FormField label="Phone Number" value={settings.company_phone} onChange={(e) => handleChange('company_phone', e.target.value)} />
                <FormField label="Website" value={settings.company_website} onChange={(e) => handleChange('company_website', e.target.value)} />
                <FormField label="Tax Registration No. (VAT/TRN)" value={settings.vat_number} onChange={(e) => handleChange('vat_number', e.target.value)} placeholder="15-digit VAT number" />
                <FormField label="Commercial Registration (CR)" value={settings.commercial_registration} onChange={(e) => handleChange('commercial_registration', e.target.value)} />
              </div>
              <FormField label="Address" value={settings.company_address} onChange={(e) => handleChange('company_address', e.target.value)} type="textarea" placeholder="Street, City, Country, PO Box..." />
              <FormField label="Logo URL (Optional)" value={settings.logo_url} onChange={(e) => handleChange('logo_url', e.target.value)} placeholder="https://..." />
            </CardContent>
          </Card>
        </TabsContent>

        {/* Accounting Settings */}
        <TabsContent value="accounting">
          <div className="grid gap-6">
            <Card>
              <CardHeader>
                <CardTitle className="flex items-center gap-2">
                  <Calculator className="h-5 w-5 text-blue-600" />
                  Financial Configuration
                </CardTitle>
              </CardHeader>
              <CardContent className="space-y-4">
                <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
                  <FormField
                    label="Default VAT Rate (%)"
                    type="select"
                    value={settings.vat_rate}
                    onChange={(e) => handleChange('vat_rate', e.target.value)}
                    options={[
                      { value: '15', label: '15% (Standard)' },
                      { value: '5', label: '5%' },
                      { value: '0', label: '0% (Zero Rated)' }
                    ]}
                  />
                  <FormField
                    label="Fiscal Year Start"
                    type="select"
                    value={settings.fiscal_year_start}
                    onChange={(e) => handleChange('fiscal_year_start', e.target.value)}
                    options={[
                      { value: '01', label: 'January' },
                      { value: '04', label: 'April' },
                      { value: '07', label: 'July' },
                      { value: '10', label: 'October' }
                    ]}
                  />
                  <FormField
                    label="Decimal Places"
                    type="select"
                    value={settings.decimal_places}
                    onChange={(e) => handleChange('decimal_places', e.target.value)}
                    options={[
                      { value: '0', label: '0' },
                      { value: '2', label: '2 (Standard)' },
                      { value: '3', label: '3' },
                      { value: '4', label: '4' }
                    ]}
                  />
                </div>
              </CardContent>
            </Card>

            <Card>
              <CardHeader>
                <CardTitle className="flex items-center gap-2">
                  <Globe className="h-5 w-5 text-indigo-600" />
                  Currency Settings
                </CardTitle>
              </CardHeader>
              <CardContent>
                <div className="space-y-4">
                  <div className="flex gap-4 items-center p-4 bg-slate-50 rounded-lg border">
                    <div className="text-3xl">{settings.currency_symbol}</div>
                    <div>
                      <div className="font-bold text-lg">{settings.base_currency}</div>
                      <div className="text-sm text-slate-500">Selected Base Currency</div>
                    </div>
                  </div>
                  
                  <div className="flex flex-wrap gap-2">
                    {Object.entries(CURRENCY_SYMBOLS).map(([code, symbol]) => (
                      <Button
                        key={code}
                        variant={settings.base_currency === code ? "default" : "outline"}
                        size="sm"
                        onClick={() => {
                          handleChange('base_currency', code);
                          handleChange('currency_symbol', symbol);
                        }}
                        className={settings.base_currency === code ? "bg-blue-600" : ""}
                      >
                        {code} {symbol}
                      </Button>
                    ))}
                  </div>
                </div>
              </CardContent>
            </Card>
          </div>
        </TabsContent>

        {/* Inventory Settings */}
        <TabsContent value="inventory">
          <Card>
            <CardHeader>
              <CardTitle className="flex items-center gap-2">
                <Database className="h-5 w-5 text-purple-600" />
                Inventory Controls
              </CardTitle>
            </CardHeader>
            <CardContent className="space-y-6">
              <div className="flex items-center justify-between border-b pb-4">
                <div>
                  <Label className="text-base">Enable Inventory Management</Label>
                  <p className="text-sm text-slate-500">Track stock items, quantities, and movements</p>
                </div>
                <Switch checked={settings.enable_inventory} onCheckedChange={(c) => handleChange('enable_inventory', c)} />
              </div>

              {settings.enable_inventory && (
                <>
                  <div className="flex items-center justify-between border-b pb-4">
                    <div>
                      <Label className="text-base">Allow Negative Stock</Label>
                      <p className="text-sm text-slate-500">Allow transactions even if stock is insufficient (Warning: may cause valuation errors)</p>
                    </div>
                    <Switch checked={settings.enable_negative_stock} onCheckedChange={(c) => handleChange('enable_negative_stock', c)} />
                  </div>

                  <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                    <FormField
                      label="Stock Valuation Method"
                      type="select"
                      value={settings.valuation_method}
                      onChange={(e) => handleChange('valuation_method', e.target.value)}
                      options={[
                        { value: 'FIFO', label: 'First In, First Out (FIFO)' },
                        { value: 'LIFO', label: 'Last In, First Out (LIFO)' },
                        { value: 'AVG', label: 'Weighted Average' }
                      ]}
                    />
                  </div>

                  <div className="flex items-center justify-between pt-2">
                    <div>
                      <Label>Batch / Lot Tracking</Label>
                      <p className="text-xs text-slate-500">Track expiry dates and batch numbers</p>
                    </div>
                    <Switch checked={settings.enable_batches} onCheckedChange={(c) => handleChange('enable_batches', c)} />
                  </div>
                </>
              )}
            </CardContent>
          </Card>
        </TabsContent>

        {/* Voucher Settings */}
        <TabsContent value="vouchers">
          <Card>
            <CardHeader>
              <CardTitle className="flex items-center gap-2">
                <FileText className="h-5 w-5 text-orange-600" />
                Numbering & Prefixes
              </CardTitle>
              <CardDescription>Customize how your transaction documents are numbered</CardDescription>
            </CardHeader>
            <CardContent className="space-y-6">
              <div className="flex items-center justify-between border-b pb-4">
                <div>
                  <Label className="text-base">Auto-Generate Voucher Numbers</Label>
                  <p className="text-sm text-slate-500">System will automatically assign sequential numbers</p>
                </div>
                <Switch checked={settings.auto_voucher_numbering} onCheckedChange={(c) => handleChange('auto_voucher_numbering', c)} />
              </div>

              <div className="grid grid-cols-2 md:grid-cols-3 gap-4">
                <FormField label="Sales Invoice Prefix" value={settings.invoice_prefix} onChange={(e) => handleChange('invoice_prefix', e.target.value)} />
                <FormField label="Purchase Invoice Prefix" value={settings.purchase_prefix} onChange={(e) => handleChange('purchase_prefix', e.target.value)} />
                <FormField label="Receipt Prefix" value={settings.receipt_prefix} onChange={(e) => handleChange('receipt_prefix', e.target.value)} />
                <FormField label="Payment Prefix" value={settings.payment_prefix} onChange={(e) => handleChange('payment_prefix', e.target.value)} />
                <FormField label="Journal Prefix" value={settings.journal_prefix} onChange={(e) => handleChange('journal_prefix', e.target.value)} />
              </div>
            </CardContent>
          </Card>
          
          <Card className="mt-6">
            <CardHeader>
              <CardTitle className="flex items-center gap-2">
                <Printer className="h-5 w-5 text-slate-600" />
                Print Configuration
              </CardTitle>
            </CardHeader>
            <CardContent className="space-y-4">
              <FormField 
                label="Default Terms & Conditions" 
                type="textarea" 
                rows={4}
                value={settings.invoice_terms} 
                onChange={(e) => handleChange('invoice_terms', e.target.value)} 
                placeholder="Enter default terms to appear on invoices..."
              />
              <FormField 
                label="Invoice Footer Note" 
                value={settings.invoice_footer} 
                onChange={(e) => handleChange('invoice_footer', e.target.value)} 
              />
            </CardContent>
          </Card>
        </TabsContent>

        {/* System Settings */}
        <TabsContent value="system">
          <Card>
            <CardHeader>
              <CardTitle className="flex items-center gap-2">
                <ShieldCheck className="h-5 w-5 text-red-600" />
                Module Access
              </CardTitle>
            </CardHeader>
            <CardContent className="space-y-6">
              <div className="flex items-center justify-between">
                <div>
                  <Label>Payroll Management</Label>
                  <p className="text-sm text-slate-500">Enable salary, employee, and payslip management</p>
                </div>
                <Switch checked={settings.enable_payroll} onCheckedChange={(c) => handleChange('enable_payroll', c)} />
              </div>
              
              <div className="flex items-center justify-between">
                <div>
                  <Label>Cost Centers</Label>
                  <p className="text-sm text-slate-500">Track revenue and expenses by department/project</p>
                </div>
                <Switch checked={settings.enable_cost_centers} onCheckedChange={(c) => handleChange('enable_cost_centers', c)} />
              </div>

              <div className="flex items-center justify-between">
                <div>
                  <Label>Require Narration</Label>
                  <p className="text-sm text-slate-500">Force users to enter comments/narration for every transaction</p>
                </div>
                <Switch checked={settings.require_narration} onCheckedChange={(c) => handleChange('require_narration', c)} />
              </div>
            </CardContent>
          </Card>

          <Card className="mt-6">
            <CardHeader>
              <CardTitle>System Info</CardTitle>
            </CardHeader>
            <CardContent>
               <div className="space-y-2 text-sm text-slate-600">
                <div className="flex justify-between py-2 border-b">
                  <span>RCAS Version</span>
                  <span className="font-mono">1.2.0-beta</span>
                </div>
                <div className="flex justify-between py-2 border-b">
                  <span>Database Status</span>
                  <span className="text-emerald-600 font-medium">Connected (Local)</span>
                </div>
                <div className="flex justify-between py-2 border-b">
                  <span>Last Backup</span>
                  <span>Never</span>
                </div>
              </div>
            </CardContent>
          </Card>
        </TabsContent>
        </>
      )}
      </Tabs>

      {activeTab !== 'security' && hasRole([ROLES.SUPER_ADMIN]) && (
      <div className="fixed bottom-0 left-0 right-0 p-4 bg-white dark:bg-slate-900 border-t flex justify-end gap-4 shadow-lg z-50 md:pl-64">
        <Button variant="outline" onClick={() => window.history.back()}>Cancel</Button>
        <Button type="button" onClick={handleSave} className="bg-emerald-600 hover:bg-emerald-700 w-32">
          {saveMutation.isPending ? <LoadingSpinner size="sm" /> : (
            <>
              <Save className="h-4 w-4 mr-2" />
              Save
            </>
          )}
        </Button>
      </div>
      )}
    </div>
  );
}
