import React, { useState, useEffect } from 'react';
import { base44 } from '@/api/base44Client';
import { useQuery, useMutation, useQueryClient } from '@tanstack/react-query';
import { useCurrency } from '@/context/CurrencyContext';
import PageHeader from '@/components/common/PageHeader';
import FormField from '@/components/forms/FormField';
import LoadingSpinner from '@/components/common/LoadingSpinner';
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from "@/components/ui/card";
import { Switch } from "@/components/ui/switch";
import { Label } from "@/components/ui/label";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { toast } from "sonner";
import { 
  Settings, Save, Database, FileText, Calculator, Globe, 
  Building2, Receipt, ShieldCheck, Printer
} from 'lucide-react';

export default function AppSettings() {
  const queryClient = useQueryClient();
  const { baseCurrency, baseCurrencySymbol, setSelectedCurrency, CURRENCY_SYMBOLS } = useCurrency();
  const [activeTab, setActiveTab] = useState('company');
  
  const defaultSettings = {
    // Company Info
    company_name: '',
    company_address: '',
    company_phone: '',
    company_email: '',
    company_website: '',
    vat_number: '', // TRN
    commercial_registration: '', // CR Number
    logo_url: '',

    // Accounting & Currency
    base_currency: 'SAR',
    currency_symbol: '﷼',
    decimal_places: '2',
    date_format: 'dd/MM/yyyy',
    fiscal_year_start: '01',
    vat_rate: '15',
    
    // Inventory
    enable_inventory: true,
    enable_negative_stock: false,
    valuation_method: 'FIFO',
    enable_batches: false,
    enable_expiry: false,

    // Vouchers & Prefixes
    auto_voucher_numbering: true,
    invoice_prefix: 'INV',
    purchase_prefix: 'PUR',
    receipt_prefix: 'REC',
    payment_prefix: 'PAY',
    journal_prefix: 'JNL',
    
    // Modules & Features
    enable_payroll: true,
    enable_cost_centers: false,
    require_narration: false,
    
    // Print Settings
    invoice_terms: 'Payment is due within 30 days.\nThank you for your business.',
    invoice_footer: 'Generated by RCAS System'
  };

  const [settings, setSettings] = useState(defaultSettings);
  const [settingsId, setSettingsId] = useState(null);

  // Load Settings
  const { data: existingSettings, isLoading } = useQuery({
    queryKey: ['settings'],
    queryFn: async () => {
      const list = await base44.entities.Settings.list();
      return list.length > 0 ? list[0] : null;
    }
  });

  useEffect(() => {
    if (existingSettings) {
      setSettings(prev => ({ ...prev, ...existingSettings }));
      setSettingsId(existingSettings.id);
      
      // Sync currency context if needed
      if (existingSettings.base_currency && existingSettings.base_currency !== baseCurrency) {
        setSelectedCurrency(existingSettings.base_currency, existingSettings.currency_symbol || CURRENCY_SYMBOLS[existingSettings.base_currency]);
      }
    }
  }, [existingSettings, baseCurrency, setSelectedCurrency, CURRENCY_SYMBOLS]);

  const saveMutation = useMutation({
    mutationFn: async (newSettings) => {
      if (settingsId) {
        return base44.entities.Settings.update(settingsId, newSettings);
      } else {
        return base44.entities.Settings.create(newSettings);
      }
    },
    onSuccess: (data) => {
      setSettingsId(data.id);
      queryClient.invalidateQueries(['settings']);
      toast.success('Settings saved successfully');
      
      // Update global context
      setSelectedCurrency(settings.base_currency, settings.currency_symbol);
    },
    onError: () => {
      toast.error('Failed to save settings');
    }
  });

  const handleChange = (field, value) => {
    setSettings(prev => ({ ...prev, [field]: value }));
  };

  const handleSave = () => {
    saveMutation.mutate(settings);
  };

  if (isLoading) return <LoadingSpinner />;

  return (
    <div className="max-w-5xl mx-auto pb-10">
      <PageHeader 
        title="App Settings" 
        subtitle="Configure system preferences, company details, and modules" 
        icon={Settings}
      />

      <Tabs value={activeTab} onValueChange={setActiveTab} className="space-y-6">
        <TabsList className="grid w-full grid-cols-2 md:grid-cols-5 h-auto">
          <TabsTrigger value="company" className="py-3">Company</TabsTrigger>
          <TabsTrigger value="accounting" className="py-3">Accounting</TabsTrigger>
          <TabsTrigger value="inventory" className="py-3">Inventory</TabsTrigger>
          <TabsTrigger value="vouchers" className="py-3">Vouchers</TabsTrigger>
          <TabsTrigger value="system" className="py-3">System</TabsTrigger>
        </TabsList>

        {/* Company Settings */}
        <TabsContent value="company">
          <Card>
            <CardHeader>
              <CardTitle className="flex items-center gap-2">
                <Building2 className="h-5 w-5 text-emerald-600" />
                Company Information
              </CardTitle>
              <CardDescription>Details that appear on your invoices and reports</CardDescription>
            </CardHeader>
            <CardContent className="space-y-4">
              <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                <FormField label="Company Name" value={settings.company_name} onChange={(e) => handleChange('company_name', e.target.value)} placeholder="e.g. Al-Rustam Trading Co." />
                <FormField label="Email Address" value={settings.company_email} onChange={(e) => handleChange('company_email', e.target.value)} type="email" />
                <FormField label="Phone Number" value={settings.company_phone} onChange={(e) => handleChange('company_phone', e.target.value)} />
                <FormField label="Website" value={settings.company_website} onChange={(e) => handleChange('company_website', e.target.value)} />
                <FormField label="Tax Registration No. (VAT/TRN)" value={settings.vat_number} onChange={(e) => handleChange('vat_number', e.target.value)} placeholder="15-digit VAT number" />
                <FormField label="Commercial Registration (CR)" value={settings.commercial_registration} onChange={(e) => handleChange('commercial_registration', e.target.value)} />
              </div>
              <FormField label="Address" value={settings.company_address} onChange={(e) => handleChange('company_address', e.target.value)} type="textarea" placeholder="Street, City, Country, PO Box..." />
              <FormField label="Logo URL (Optional)" value={settings.logo_url} onChange={(e) => handleChange('logo_url', e.target.value)} placeholder="https://..." />
            </CardContent>
          </Card>
        </TabsContent>

        {/* Accounting Settings */}
        <TabsContent value="accounting">
          <div className="grid gap-6">
            <Card>
              <CardHeader>
                <CardTitle className="flex items-center gap-2">
                  <Calculator className="h-5 w-5 text-blue-600" />
                  Financial Configuration
                </CardTitle>
              </CardHeader>
              <CardContent className="space-y-4">
                <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
                  <FormField
                    label="Default VAT Rate (%)"
                    type="select"
                    value={settings.vat_rate}
                    onChange={(e) => handleChange('vat_rate', e.target.value)}
                    options={[
                      { value: '15', label: '15% (Standard)' },
                      { value: '5', label: '5%' },
                      { value: '0', label: '0% (Zero Rated)' }
                    ]}
                  />
                  <FormField
                    label="Fiscal Year Start"
                    type="select"
                    value={settings.fiscal_year_start}
                    onChange={(e) => handleChange('fiscal_year_start', e.target.value)}
                    options={[
                      { value: '01', label: 'January' },
                      { value: '04', label: 'April' },
                      { value: '07', label: 'July' },
                      { value: '10', label: 'October' }
                    ]}
                  />
                  <FormField
                    label="Decimal Places"
                    type="select"
                    value={settings.decimal_places}
                    onChange={(e) => handleChange('decimal_places', e.target.value)}
                    options={[
                      { value: '0', label: '0' },
                      { value: '2', label: '2 (Standard)' },
                      { value: '3', label: '3' },
                      { value: '4', label: '4' }
                    ]}
                  />
                </div>
              </CardContent>
            </Card>

            <Card>
              <CardHeader>
                <CardTitle className="flex items-center gap-2">
                  <Globe className="h-5 w-5 text-indigo-600" />
                  Currency Settings
                </CardTitle>
              </CardHeader>
              <CardContent>
                <div className="space-y-4">
                  <div className="flex gap-4 items-center p-4 bg-slate-50 rounded-lg border">
                    <div className="text-3xl">{settings.currency_symbol}</div>
                    <div>
                      <div className="font-bold text-lg">{settings.base_currency}</div>
                      <div className="text-sm text-slate-500">Selected Base Currency</div>
                    </div>
                  </div>
                  
                  <div className="flex flex-wrap gap-2">
                    {Object.entries(CURRENCY_SYMBOLS).map(([code, symbol]) => (
                      <Button
                        key={code}
                        variant={settings.base_currency === code ? "default" : "outline"}
                        size="sm"
                        onClick={() => {
                          handleChange('base_currency', code);
                          handleChange('currency_symbol', symbol);
                        }}
                        className={settings.base_currency === code ? "bg-blue-600" : ""}
                      >
                        {code} {symbol}
                      </Button>
                    ))}
                  </div>
                </div>
              </CardContent>
            </Card>
          </div>
        </TabsContent>

        {/* Inventory Settings */}
        <TabsContent value="inventory">
          <Card>
            <CardHeader>
              <CardTitle className="flex items-center gap-2">
                <Database className="h-5 w-5 text-purple-600" />
                Inventory Controls
              </CardTitle>
            </CardHeader>
            <CardContent className="space-y-6">
              <div className="flex items-center justify-between border-b pb-4">
                <div>
                  <Label className="text-base">Enable Inventory Management</Label>
                  <p className="text-sm text-slate-500">Track stock items, quantities, and movements</p>
                </div>
                <Switch checked={settings.enable_inventory} onCheckedChange={(c) => handleChange('enable_inventory', c)} />
              </div>

              {settings.enable_inventory && (
                <>
                  <div className="flex items-center justify-between border-b pb-4">
                    <div>
                      <Label className="text-base">Allow Negative Stock</Label>
                      <p className="text-sm text-slate-500">Allow transactions even if stock is insufficient (Warning: may cause valuation errors)</p>
                    </div>
                    <Switch checked={settings.enable_negative_stock} onCheckedChange={(c) => handleChange('enable_negative_stock', c)} />
                  </div>

                  <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                    <FormField
                      label="Stock Valuation Method"
                      type="select"
                      value={settings.valuation_method}
                      onChange={(e) => handleChange('valuation_method', e.target.value)}
                      options={[
                        { value: 'FIFO', label: 'First In, First Out (FIFO)' },
                        { value: 'LIFO', label: 'Last In, First Out (LIFO)' },
                        { value: 'AVG', label: 'Weighted Average' }
                      ]}
                    />
                  </div>

                  <div className="flex items-center justify-between pt-2">
                    <div>
                      <Label>Batch / Lot Tracking</Label>
                      <p className="text-xs text-slate-500">Track expiry dates and batch numbers</p>
                    </div>
                    <Switch checked={settings.enable_batches} onCheckedChange={(c) => handleChange('enable_batches', c)} />
                  </div>
                </>
              )}
            </CardContent>
          </Card>
        </TabsContent>

        {/* Voucher Settings */}
        <TabsContent value="vouchers">
          <Card>
            <CardHeader>
              <CardTitle className="flex items-center gap-2">
                <FileText className="h-5 w-5 text-orange-600" />
                Numbering & Prefixes
              </CardTitle>
              <CardDescription>Customize how your transaction documents are numbered</CardDescription>
            </CardHeader>
            <CardContent className="space-y-6">
              <div className="flex items-center justify-between border-b pb-4">
                <div>
                  <Label className="text-base">Auto-Generate Voucher Numbers</Label>
                  <p className="text-sm text-slate-500">System will automatically assign sequential numbers</p>
                </div>
                <Switch checked={settings.auto_voucher_numbering} onCheckedChange={(c) => handleChange('auto_voucher_numbering', c)} />
              </div>

              <div className="grid grid-cols-2 md:grid-cols-3 gap-4">
                <FormField label="Sales Invoice Prefix" value={settings.invoice_prefix} onChange={(e) => handleChange('invoice_prefix', e.target.value)} />
                <FormField label="Purchase Invoice Prefix" value={settings.purchase_prefix} onChange={(e) => handleChange('purchase_prefix', e.target.value)} />
                <FormField label="Receipt Prefix" value={settings.receipt_prefix} onChange={(e) => handleChange('receipt_prefix', e.target.value)} />
                <FormField label="Payment Prefix" value={settings.payment_prefix} onChange={(e) => handleChange('payment_prefix', e.target.value)} />
                <FormField label="Journal Prefix" value={settings.journal_prefix} onChange={(e) => handleChange('journal_prefix', e.target.value)} />
              </div>
            </CardContent>
          </Card>
          
          <Card className="mt-6">
            <CardHeader>
              <CardTitle className="flex items-center gap-2">
                <Printer className="h-5 w-5 text-slate-600" />
                Print Configuration
              </CardTitle>
            </CardHeader>
            <CardContent className="space-y-4">
              <FormField 
                label="Default Terms & Conditions" 
                type="textarea" 
                rows={4}
                value={settings.invoice_terms} 
                onChange={(e) => handleChange('invoice_terms', e.target.value)} 
                placeholder="Enter default terms to appear on invoices..."
              />
              <FormField 
                label="Invoice Footer Note" 
                value={settings.invoice_footer} 
                onChange={(e) => handleChange('invoice_footer', e.target.value)} 
              />
            </CardContent>
          </Card>
        </TabsContent>

        {/* System Settings */}
        <TabsContent value="system">
          <Card>
            <CardHeader>
              <CardTitle className="flex items-center gap-2">
                <ShieldCheck className="h-5 w-5 text-red-600" />
                Module Access
              </CardTitle>
            </CardHeader>
            <CardContent className="space-y-6">
              <div className="flex items-center justify-between">
                <div>
                  <Label>Payroll Management</Label>
                  <p className="text-sm text-slate-500">Enable salary, employee, and payslip management</p>
                </div>
                <Switch checked={settings.enable_payroll} onCheckedChange={(c) => handleChange('enable_payroll', c)} />
              </div>
              
              <div className="flex items-center justify-between">
                <div>
                  <Label>Cost Centers</Label>
                  <p className="text-sm text-slate-500">Track revenue and expenses by department/project</p>
                </div>
                <Switch checked={settings.enable_cost_centers} onCheckedChange={(c) => handleChange('enable_cost_centers', c)} />
              </div>

              <div className="flex items-center justify-between">
                <div>
                  <Label>Require Narration</Label>
                  <p className="text-sm text-slate-500">Force users to enter comments/narration for every transaction</p>
                </div>
                <Switch checked={settings.require_narration} onCheckedChange={(c) => handleChange('require_narration', c)} />
              </div>
            </CardContent>
          </Card>

          <Card className="mt-6">
            <CardHeader>
              <CardTitle>System Info</CardTitle>
            </CardHeader>
            <CardContent>
               <div className="space-y-2 text-sm text-slate-600">
                <div className="flex justify-between py-2 border-b">
                  <span>RCAS Version</span>
                  <span className="font-mono">1.2.0-beta</span>
                </div>
                <div className="flex justify-between py-2 border-b">
                  <span>Database Status</span>
                  <span className="text-emerald-600 font-medium">Connected (Local)</span>
                </div>
                <div className="flex justify-between py-2 border-b">
                  <span>Last Backup</span>
                  <span>Never</span>
                </div>
              </div>
            </CardContent>
          </Card>
        </TabsContent>
      </Tabs>

      <div className="fixed bottom-0 left-0 right-0 p-4 bg-white dark:bg-slate-900 border-t flex justify-end gap-4 shadow-lg z-50 md:pl-64">
        <Button variant="outline" onClick={() => window.history.back()}>Cancel</Button>
        <Button onClick={handleSave} className="bg-emerald-600 hover:bg-emerald-700 w-32">
          {saveMutation.isPending ? <LoadingSpinner size="sm" /> : (
            <>
              <Save className="h-4 w-4 mr-2" />
              Save
            </>
          )}
        </Button>
      </div>
    </div>
  );
}
