-- Enable UUID extension
create extension if not exists "uuid-ossp";

-- PROFILES (Extends Supabase Auth)
create table public.profiles (
  id uuid references auth.users not null primary key,
  email text,
  full_name text,
  role text default 'User',
  allowed_companies text[], -- Array of Company IDs
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- RLS for Profiles
alter table public.profiles enable row level security;
create policy "Public profiles are viewable by everyone." on public.profiles for select using (true);
create policy "Users can insert their own profile." on public.profiles for insert with check (auth.uid() = id);
create policy "Users can update own profile." on public.profiles for update using (auth.uid() = id);

-- Trigger to create profile on signup
create or replace function public.handle_new_user() 
returns trigger as $$
begin
  insert into public.profiles (id, email, full_name, role)
  values (new.id, new.email, new.raw_user_meta_data->>'full_name', coalesce(new.raw_user_meta_data->>'role', 'User'));
  return new;
end;
$$ language plpgsql security definer;

create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();


-- COMPANIES
create table public.companies (
  id bigint generated by default as identity primary key,
  name text not null,
  name_arabic text,
  address text,
  city text,
  country text default 'Saudi Arabia',
  postal_code text,
  phone text,
  email text,
  website text,
  vat_number text,
  cr_number text,
  financial_year_start date,
  financial_year_end date,
  currency text default 'SAR',
  logo_url text,
  business_type text default 'Retail',
  password text, -- Simple password for protection
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- BRANCHES
create table public.branches (
  id bigint generated by default as identity primary key,
  company_id bigint references public.companies(id) on delete cascade,
  name text not null,
  name_arabic text,
  code text,
  address text,
  city text,
  phone text,
  email text,
  manager_name text,
  is_main boolean default false,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- SETTINGS
create table public.settings (
  id bigint generated by default as identity primary key,
  company_name text,
  base_currency text,
  currency_symbol text,
  auto_voucher_numbering boolean default true,
  invoice_prefix text,
  purchase_prefix text,
  receipt_prefix text,
  payment_prefix text,
  journal_prefix text,
  enable_payroll boolean default true,
  enable_cost_centers boolean default false,
  require_narration boolean default false,
  invoice_terms text,
  invoice_footer text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- CURRENCIES
create table public.currencies (
  id bigint generated by default as identity primary key,
  code text not null,
  name text,
  symbol text,
  exchange_rate numeric,
  is_base boolean default false,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- GENERIC TABLES (Simplified for other entities)
-- In a real app, you'd define specific columns for each. 
-- For rapid prototyping compatible with the flexible NoSQL-like localStorage adapter, 
-- we can use JSONB for flexible fields or define them strictly.
-- Given the time, I'll define key tables strictly and others as needed.

-- ACCOUNT GROUPS
create table public.account_groups (
  id bigint generated by default as identity primary key,
  company_id bigint references public.companies(id) on delete cascade,
  name text not null,
  parent_id bigint references public.account_groups(id),
  type text, -- Asset, Liability, Income, Expense
  is_primary boolean default false,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- LEDGERS
create table public.ledgers (
  id bigint generated by default as identity primary key,
  company_id bigint references public.companies(id) on delete cascade,
  name text not null,
  group_id bigint references public.account_groups(id),
  opening_balance numeric default 0,
  opening_balance_type text, -- Dr/Cr
  current_balance numeric default 0,
  email text,
  phone text,
  address text,
  tax_number text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- VOUCHERS
create table public.vouchers (
  id bigint generated by default as identity primary key,
  company_id bigint references public.companies(id) on delete cascade,
  branch_id bigint references public.branches(id),
  voucher_type text, -- Sales, Purchase, Payment, Receipt, Journal, Contra
  voucher_number text,
  date date,
  reference_number text,
  narration text,
  total_amount numeric default 0,
  party_ledger_id bigint references public.ledgers(id),
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- VOUCHER ITEMS (Inventory details)
create table public.voucher_items (
  id bigint generated by default as identity primary key,
  company_id bigint references public.companies(id) on delete cascade,
  voucher_id bigint references public.vouchers(id) on delete cascade,
  item_id bigint, -- References stock_items
  quantity numeric,
  rate numeric,
  amount numeric,
  discount numeric,
  tax_amount numeric,
  godown_id bigint, -- References godowns
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- VOUCHER LEDGER ENTRIES (Accounting details)
create table public.voucher_ledger_entries (
  id bigint generated by default as identity primary key,
  company_id bigint references public.companies(id) on delete cascade,
  voucher_id bigint references public.vouchers(id) on delete cascade,
  ledger_id bigint references public.ledgers(id),
  amount numeric,
  type text, -- Dr/Cr
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- STOCK GROUPS
create table public.stock_groups (
  id bigint generated by default as identity primary key,
  company_id bigint references public.companies(id) on delete cascade,
  name text not null,
  parent_id bigint references public.stock_groups(id),
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- UNITS
create table public.units (
  id bigint generated by default as identity primary key,
  company_id bigint references public.companies(id) on delete cascade,
  name text not null,
  symbol text,
  decimal_places integer default 0,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- STOCK ITEMS
create table public.stock_items (
  id bigint generated by default as identity primary key,
  company_id bigint references public.companies(id) on delete cascade,
  name text not null,
  group_id bigint references public.stock_groups(id),
  unit_id bigint references public.units(id),
  opening_quantity numeric default 0,
  opening_rate numeric default 0,
  opening_value numeric default 0,
  selling_price numeric default 0,
  cost_price numeric default 0,
  part_number text,
  description text,
  reorder_level numeric,
  image_url text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- GODOWNS
create table public.godowns (
  id bigint generated by default as identity primary key,
  company_id bigint references public.companies(id) on delete cascade,
  name text not null,
  address text,
  is_primary boolean default false,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- COST CENTERS
create table public.cost_centers (
  id bigint generated by default as identity primary key,
  company_id bigint references public.companies(id) on delete cascade,
  name text not null,
  parent_id bigint references public.cost_centers(id),
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- EMPLOYEES
create table public.employees (
  id bigint generated by default as identity primary key,
  company_id bigint references public.companies(id) on delete cascade,
  name text not null,
  employee_id text,
  designation text,
  department text,
  date_of_joining date,
  basic_salary numeric,
  email text,
  phone text,
  status text default 'Active',
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- SALARY COMPONENTS
create table public.salary_components (
  id bigint generated by default as identity primary key,
  company_id bigint references public.companies(id) on delete cascade,
  name text not null,
  type text, -- Earning/Deduction
  calculation_type text, -- Flat/Percentage
  value numeric,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- PAYROLL
create table public.payroll (
  id bigint generated by default as identity primary key,
  company_id bigint references public.companies(id) on delete cascade,
  employee_id bigint references public.employees(id),
  month text,
  year integer,
  basic_salary numeric,
  total_earnings numeric,
  total_deductions numeric,
  net_salary numeric,
  payment_date date,
  status text, -- Paid/Pending
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable RLS on all tables (Basic Policy: Public access for demo, or authenticated)
-- For this MVP/Demo, we'll allow public access to simplify connection, 
-- but in production you should restrict based on company_id and user_id.
alter table public.companies enable row level security;
create policy "Allow all access" on public.companies for all using (true);

alter table public.branches enable row level security;
create policy "Allow all access" on public.branches for all using (true);

alter table public.settings enable row level security;
create policy "Allow all access" on public.settings for all using (true);

alter table public.currencies enable row level security;
create policy "Allow all access" on public.currencies for all using (true);

alter table public.account_groups enable row level security;
create policy "Allow all access" on public.account_groups for all using (true);

alter table public.ledgers enable row level security;
create policy "Allow all access" on public.ledgers for all using (true);

alter table public.vouchers enable row level security;
create policy "Allow all access" on public.vouchers for all using (true);

alter table public.voucher_items enable row level security;
create policy "Allow all access" on public.voucher_items for all using (true);

alter table public.voucher_ledger_entries enable row level security;
create policy "Allow all access" on public.voucher_ledger_entries for all using (true);

alter table public.stock_groups enable row level security;
create policy "Allow all access" on public.stock_groups for all using (true);

alter table public.stock_items enable row level security;
create policy "Allow all access" on public.stock_items for all using (true);

alter table public.units enable row level security;
create policy "Allow all access" on public.units for all using (true);

alter table public.godowns enable row level security;
create policy "Allow all access" on public.godowns for all using (true);

alter table public.cost_centers enable row level security;
create policy "Allow all access" on public.cost_centers for all using (true);

alter table public.employees enable row level security;
create policy "Allow all access" on public.employees for all using (true);

alter table public.salary_components enable row level security;
create policy "Allow all access" on public.salary_components for all using (true);

alter table public.payroll enable row level security;
create policy "Allow all access" on public.payroll for all using (true);


-- VOUCHER TYPES
create table public.voucher_types (
  id bigint generated by default as identity primary key,
  company_id bigint references public.companies(id) on delete cascade,
  name text not null,
  parent_type text, -- Sales, Purchase, etc.
  numbering_method text, -- Automatic/Manual
  prefix text,
  suffix text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- CUSTODY WALLETS
create table public.custody_wallets (
  id bigint generated by default as identity primary key,
  company_id bigint references public.companies(id) on delete cascade,
  employee_id bigint references public.employees(id),
  balance numeric default 0,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- CUSTODY TRANSACTIONS
create table public.custody_transactions (
  id bigint generated by default as identity primary key,
  company_id bigint references public.companies(id) on delete cascade,
  wallet_id bigint references public.custody_wallets(id) on delete cascade,
  amount numeric,
  type text, -- Add/Spend
  description text,
  receipt_url text,
  date date,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- FLOWER WASTE (Specific feature)
create table public.flower_waste (
  id bigint generated by default as identity primary key,
  company_id bigint references public.companies(id) on delete cascade,
  date date,
  item_name text,
  quantity numeric,
  reason text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- BANK RECONCILIATION
create table public.bank_reconciliations (
  id bigint generated by default as identity primary key,
  company_id bigint references public.companies(id) on delete cascade,
  ledger_id bigint references public.ledgers(id),
  statement_date date,
  closing_balance numeric,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- ZATCA INVOICES
create table public.zatca_invoices (
  id bigint generated by default as identity primary key,
  company_id bigint references public.companies(id) on delete cascade,
  voucher_id bigint references public.vouchers(id),
  uuid text,
  hash text,
  previous_hash text,
  status text, -- Reported/Failed
  xml_content text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- BRANCH DAILY RECORDS
create table public.branch_daily_records (
  id bigint generated by default as identity primary key,
  company_id bigint references public.companies(id) on delete cascade,
  branch_id bigint references public.branches(id) on delete cascade,
  date date,
  opening_cash numeric,
  closing_cash numeric,
  total_sales numeric,
  total_expenses numeric,
  status text, -- Open/Closed
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- RLS Policies for new tables
alter table public.voucher_types enable row level security;
create policy "Allow all access" on public.voucher_types for all using (true);

alter table public.custody_wallets enable row level security;
create policy "Allow all access" on public.custody_wallets for all using (true);

alter table public.custody_transactions enable row level security;
create policy "Allow all access" on public.custody_transactions for all using (true);

alter table public.flower_waste enable row level security;
create policy "Allow all access" on public.flower_waste for all using (true);

alter table public.bank_reconciliations enable row level security;
create policy "Allow all access" on public.bank_reconciliations for all using (true);

alter table public.zatca_invoices enable row level security;
create policy "Allow all access" on public.zatca_invoices for all using (true);

alter table public.branch_daily_records enable row level security;
create policy "Allow all access" on public.branch_daily_records for all using (true);

